//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public System.Guid request_id { get; set; }
        public System.DateTime request_datetime { get; set; }
        public string hospital_number { get; set; }
        public string request_type { get; set; }
        public System.DateTime date_of_birth { get; set; }
    }
}
